### ISSUE TITLE
Any thoughts of porting it to android?

### ISSUE THREAD

**Issue by asperon** [Killerardvark/CryodexSource#22]
Seeing as its written in Java it should be possible to just port the GUI over and let the rest of the application be?

**Comment by Killerardvark** [comment]
Currently the GUI is fairly integrated with the logic. I've done some work to separate these, but it is still pretty intertwined.

Creating an android application is not something I've ventured into yet. First, I don't have experience doing android apps. I'm sure it wouldn't be hard to figure out, but it's just easier to tell my friends/family/acquaintances that no i can't write your damn app because I don't know how to :). Second, there already is an X-Wing tournament app on android that I heard runs fairly well though I haven't tried it yet. I'm completely open to any android developer branching off of this project in an effort to create an android version. Go for it!

**Comment by kingargyle** [comment]
I have it on my todo list.  But as @Killerardvark has said the UI and core logic are intertwined.  This really needs to be seperated better into a core module so that items like an Android app, and a web application can be created.

**Comment by Killerardvark** [comment]
Update, this is being done. There's a gofundme for the project and I post updates over there. I have a beta version ready if anyone is interested in playing with it. Let me know and I'll get you a copy.

https://www.gofundme.com/263kycs
